---
- name: Add Nodesource repository
  get_url:
    url: https://rpm.nodesource.com/setup_14.x
    dest: /tmp/setup_14.sh

- name: Run Nodesource setup script
  command: bash /tmp/setup_14.sh
  args:
    creates: /etc/yum.repos.d/nodesource.repo

- name: Install Node.js
  yum:
    name: nodejs
    state: present