---
- name: "Installing xpaste application"
  hosts: "application-server"
  become: true
  vars:
    db_user: "xpaste_user"
    db_password: "xpaste_password"
    db_name: "xpaste_db"
    secret_key_base: "your_secret_key_base"

  roles:
  - postgresql
  - ruby-app-role
  - geerlingguy.nginx

  tasks:
  - name: "Copy custom nginx configuration"
    ansible.builtin.copy:
      src: "files/xpaste_practicum/config/nginx.conf"
      dest: "/etc/nginx/nginx.conf"
      mode: '0644'

  - name: "Reload nginx"
    ansible.builtin.service:
      name: "nginx"
      state: "reloaded"
